[package]
name = "pirate-sea-jam"
version = "0.7.3"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.11"
bevy_rapier3d = "0.22.0"
rand = "0.8.5"

# Optimize for WASM builds for size (see https://bevy-cheatbook.github.io/platforms/wasm/size-opt.html)
[profile.release]
opt-level = 's'
lto = "thin"
